export type DailyCaptureWindow = {
  startsAt: Date
  endsAt: Date
}
export type DailyCapturePhase = 'upcoming' | 'open' | 'closed' | 'complete'

const DAY_START_MINUTES = 9 * 60
const DAY_END_MINUTES = 21 * 60
const DEFAULT_WINDOW_MINUTES = 15

function localDateKey(date: Date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function hashString(value: string) {
  let hash = 2166136261

  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index)
    hash = Math.imul(hash, 16777619)
  }

  return hash >>> 0
}

/**
 * Produces one stable, pseudo-random window for a local calendar day.
 *
 * This is suitable for an offline prototype only. A real family-wide prompt must
 * be generated by a shared backend so every device receives the same time.
 */
export function createDailyCaptureWindow(
  day: Date,
  familySeed = 'kinsphere-demo-family',
  durationMinutes = DEFAULT_WINDOW_MINUTES,
): DailyCaptureWindow {
  const safeDuration = Math.max(1, Math.min(durationMinutes, 60))
  const latestStart = DAY_END_MINUTES - safeDuration
  const possibleStartMinutes = latestStart - DAY_START_MINUTES + 1
  const startMinute = DAY_START_MINUTES
    + (hashString(`${familySeed}:${localDateKey(day)}`) % possibleStartMinutes)

  const startsAt = new Date(day)
  startsAt.setHours(Math.floor(startMinute / 60), startMinute % 60, 0, 0)

  const endsAt = new Date(startsAt)
  endsAt.setMinutes(endsAt.getMinutes() + safeDuration)

  return { startsAt, endsAt }
}

export function getDailyCapturePhase(
  now: Date,
  window: DailyCaptureWindow,
  completed = false,
): DailyCapturePhase {
  if (completed) return 'complete'
  if (now.getTime() < window.startsAt.getTime()) return 'upcoming'
  if (now.getTime() >= window.endsAt.getTime()) return 'closed'
  return 'open'
}
