package com.simerfamily.kinsphere.panorama;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import android.content.Context;
import android.graphics.BitmapFactory;
import android.net.Uri;
import android.os.SystemClock;
import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;
import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.After;
import org.junit.Assume;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * Real foreground-service/inference/JNI lifecycle test. Supply -e stitchFixture with the
 * private-files copy generated by scripts/prepare-mobile-stitch-check.py. The fixture must
 * carry its synthetic marker; user captures are never inputs. No app data or source is deleted.
 * Output is copied to a unique service-result-UUID under the synthetic fixture before only
 * this test's validated UUID capture is cleaned up. stitchWidth defaults to 2048 (or 4096).
 * This verifies recovery without a live in-memory job, not a simulated whole-process kill.
 */
@RunWith(AndroidJUnit4.class)
public final class PanoramaStitchServiceInstrumentedTest {
    private static final String FIXTURE_MARKER = "Bundled concept panorama, synthetic rotation-only views with pose error";
    private final String owner = "service-test:" + UUID.randomUUID();
    private final List<File> originals = new ArrayList<>();
    private final List<byte[]> originalDigests = new ArrayList<>();
    private Context context;
    private PanoramaCaptureStore store;
    private File fixture;
    private File session;
    private String jobId;
    private boolean shellIdentity;
    private boolean safeToCleanUp;
    private int outputWidth;
    private long benchmarkStartedAt;

    @Before public void copySyntheticFixture() throws Exception {
        String path = InstrumentationRegistry.getArguments().getString("stitchFixture");
        Assume.assumeTrue("Supply the generated synthetic stitchFixture", path != null);
        Assume.assumeFalse("Never disturb an already-running assembly", PanoramaStitchService.hasActiveJob());
        context = ApplicationProvider.getApplicationContext();
        store = new PanoramaCaptureStore(context);
        outputWidth = Integer.parseInt(InstrumentationRegistry.getArguments().getString("stitchWidth", "2048"));
        assertTrue("stitchWidth must be 2048 or 4096", outputWidth == 2048 || outputWidth == 4096);
        fixture = new File(path).getCanonicalFile();
        assertTrue(fixture.getPath().startsWith(context.getFilesDir().getCanonicalPath() + File.separator));
        assertFalse("A real saved capture is never an eligible test fixture", fixture.getPath().startsWith(store.getRoot().getPath() + File.separator));
        JSONObject manifest = PanoramaCaptureStore.readJson(new File(fixture, "manifest.json"));
        assertEquals("Only the generated public concept fixture is allowed", FIXTURE_MARKER, manifest.getString("fixture"));
        JSONArray frames = manifest.getJSONArray("frames");
        assertTrue(frames.length() >= 8 && frames.length() <= 64);
        session = new File(store.getRoot(), UUID.randomUUID().toString());
        assertTrue(session.mkdir());
        PanoramaCaptureStore.validateSession(store.getRoot(), session);
        for (int index = 0; index < frames.length(); index++) {
            JSONObject frame = frames.getJSONObject(index);
            String fileName = frame.getString("fileName");
            assertEquals(fileName, new File(fileName).getName());
            assertTrue(fileName.toLowerCase(java.util.Locale.ROOT).endsWith(".jpg"));
            File source = new File(fixture, fileName).getCanonicalFile();
            assertEquals(fixture, source.getParentFile());
            assertTrue(source.isFile() && source.length() > 0 && source.length() <= 12L * 1024 * 1024);
            File copy = new File(session, fileName);
            Files.copy(source.toPath(), copy.toPath());
            byte[] before = digest(source);
            assertArrayEquals(before, digest(copy));
            originals.add(source);
            originalDigests.add(before);
            originals.add(copy);
            originalDigests.add(before);
            frame.put("uri", Uri.fromFile(copy).toString());
            frame.put("filePath", copy.getCanonicalPath());
            frame.remove("fileUrl");
            frame.remove("path");
        }
        manifest.put("ownerKey", owner).put("sessionId", session.getName()).put("state", "complete")
            .put("createdAt", System.currentTimeMillis()).put("targetCount", frames.length())
            .put("capturedCount", frames.length()).put("coverageComplete", true);
        PanoramaCaptureStore.writeJson(new File(session, "metadata.json"), manifest);
        android.util.Log.i("StitchServiceTest", "Synthetic session " + session + " owner=" + owner);
        // Instrumentation can start the same foreground service without bringing unrelated UI
        // or signed-in navigation into this test. The real service still must call startForeground.
        InstrumentationRegistry.getInstrumentation().getUiAutomation().adoptShellPermissionIdentity(
            "android.permission.START_FOREGROUND_SERVICES_FROM_BACKGROUND");
        shellIdentity = true;
    }

    @Test public void foregroundAssemblyIsIdempotentOwnerScopedAndDurablyReopenable() throws Exception {
        benchmarkStartedAt = SystemClock.elapsedRealtime();
        JSONObject initial = startTwiceOnMainThread();
        jobId = initial.getString("jobId");
        assertTrue(initial.getBoolean("offline"));
        assertTrue(initial.getBoolean("originalsRetained"));
        assertEquals(jobId, PanoramaStitchService.getJob(context, jobId, owner).getString("jobId"));
        assertThrows(Exception.class, () -> PanoramaStitchService.getJob(context, jobId, "another-owner"));
        assertThrows(Exception.class, () -> PanoramaStitchService.start(context, Uri.fromFile(session).toString(), "another-owner", outputWidth));
        JSONObject listing = store.list(owner).getJSONObject(0);
        assertEquals(jobId, listing.getJSONObject("assembly").getString("jobId"));
        assertFalse("Recovery listing must not mark a live job interrupted", "interrupted".equals(listing.getJSONObject("assembly").optString("code")));

        awaitTerminal(25 * 60_000L);
        awaitWorkerReleased();
        JSONObject completed = PanoramaStitchService.getJob(context, jobId, owner);
        // Preserve evidence even if a later quality/model assertion rejects this run.
        saveBenchmark(completed);
        assertEquals(completed.toString(), "completed", completed.getString("state"));
        assertEquals(1, completed.getDouble("progress"), 0);
        assertEquals(outputWidth, completed.getInt("width"));
        assertEquals(outputWidth / 2, completed.getInt("height"));
        assertNotNull(completed.optJSONObject("report"));
        JSONObject matching = completed.getJSONObject("report").getJSONObject("matchingDiagnostics");
        assertTrue("The benchmark must actually exercise learned inference", matching.getBoolean("aiUsed"));
        assertTrue(matching.getLong("extractionMillis") >= 0);
        assertTrue(matching.getLong("matchingMillis") >= 0);
        assertTrue(matching.getInt("inferencePairs") > 0);
        assertTrue(matching.getDouble("meanLayers") >= 1 && matching.getDouble("meanLayers") <= 9);
        assertImage(completed.getString("panoramaUrl"), outputWidth, outputWidth / 2);
        assertImage(completed.getString("thumbnailUrl"), 0, 0);
        // activeStatus is now null: these reads exercise only persisted recovery records.
        assertEquals(null, PanoramaStitchService.activeStatus(session, owner));
        JSONObject reopened = PanoramaStitchService.getJob(context, jobId, owner);
        assertEquals("completed", reopened.getString("state"));
        assertEquals(completed.getString("panoramaUrl"), reopened.getString("panoramaUrl"));
        JSONObject saved = new PanoramaCaptureStore(context).list(owner).getJSONObject(0).getJSONObject("savedResult");
        assertEquals(jobId, saved.getString("jobId"));
        assertEquals(completed.getString("panoramaUrl"), saved.getString("panoramaUrl"));
        assertOriginalsUnchanged();
        safeToCleanUp = true;
    }

    @Test public void explicitCancellationRetainsSourcesAndHasRecoverableTerminalState() throws Exception {
        benchmarkStartedAt = SystemClock.elapsedRealtime();
        // Queue and cancel in one main-thread turn, before onStartCommand can dispatch inference.
        AtomicReference<Exception> error = new AtomicReference<>();
        InstrumentationRegistry.getInstrumentation().runOnMainSync(() -> {
            try {
                jobId = PanoramaStitchService.start(context, Uri.fromFile(session).toString(), owner, outputWidth).getString("jobId");
                PanoramaStitchService.cancel(jobId, owner);
            } catch (Exception failure) { error.set(failure); }
        });
        if (error.get() != null) throw error.get();
        JSONObject cancelled = awaitTerminal(120_000);
        assertEquals(cancelled.toString(), "cancelled", cancelled.getString("state"));
        assertEquals("cancelled", cancelled.getString("code"));
        assertFalse(cancelled.has("panoramaUrl"));
        awaitWorkerReleased();
        assertEquals("cancelled", PanoramaStitchService.getJob(context, jobId, owner).getString("state"));
        assertFalse(store.list(owner).getJSONObject(0).has("savedResult"));
        assertOriginalsUnchanged();
        saveBenchmark(PanoramaStitchService.getJob(context, jobId, owner));
        safeToCleanUp = true;
    }

    private JSONObject startTwiceOnMainThread() throws Exception {
        AtomicReference<JSONObject> first = new AtomicReference<>();
        AtomicReference<JSONObject> second = new AtomicReference<>();
        AtomicReference<Exception> error = new AtomicReference<>();
        InstrumentationRegistry.getInstrumentation().runOnMainSync(() -> {
            try {
                JSONObject a = PanoramaStitchService.start(context, Uri.fromFile(session).toString(), owner, outputWidth);
                jobId = a.getString("jobId");
                JSONObject b = PanoramaStitchService.start(context, Uri.fromFile(session).toString(), owner, outputWidth);
                first.set(a);
                second.set(b);
            } catch (Exception failure) { error.set(failure); }
        });
        if (error.get() != null) throw error.get();
        assertEquals(first.get().getString("jobId"), second.get().getString("jobId"));
        assertEquals("queued", first.get().getString("state"));
        return first.get();
    }

    private void saveBenchmark(JSONObject finalStatus) throws Exception {
        assertOriginalsUnchanged();
        File result = new File(fixture, "service-result-" + UUID.randomUUID()).getCanonicalFile();
        assertEquals(fixture, result.getParentFile());
        assertTrue(result.mkdir());
        JSONObject benchmark = new JSONObject().put("fixture", FIXTURE_MARKER)
            .put("jobId", jobId).put("state", finalStatus.getString("state")).put("outputWidth", outputWidth)
            .put("frameCount", originals.size() / 2).put("originalsRetainedAfterAssembly", true)
            .put("fixtureSourcesUnchanged", true).put("sourceVerification", "SHA-256 before/after every source and copied original")
            .put("elapsedSeconds", finalStatus.optDouble("elapsedSeconds", (SystemClock.elapsedRealtime() - benchmarkStartedAt) / 1000.0))
            .put("report", finalStatus.optJSONObject("report"));
        if (finalStatus.has("code")) benchmark.put("code", finalStatus.getString("code"));
        if (finalStatus.has("error")) benchmark.put("error", finalStatus.getString("error"));
        if ("completed".equals(finalStatus.optString("state"))) {
            benchmark.put("panoramaPath", copyResultImage(finalStatus.getString("panoramaUrl"), result, "panorama.jpg").getPath());
            benchmark.put("thumbnailPath", copyResultImage(finalStatus.getString("thumbnailUrl"), result, "thumbnail.jpg").getPath());
        }
        PanoramaCaptureStore.writeJson(new File(result, "service-benchmark.json"), benchmark);
        android.util.Log.i("StitchServiceTest", "BENCHMARK " + new File(result, "service-benchmark.json") + " " + benchmark);
    }

    private File copyResultImage(String uri, File result, String name) throws Exception {
        File source = new File(Uri.parse(uri).getPath()).getCanonicalFile();
        assertEquals(session, source.getParentFile().getParentFile());
        File output = new File(result, name);
        Files.copy(source.toPath(), output.toPath());
        assertArrayEquals(digest(source), digest(output));
        return output;
    }

    private JSONObject awaitTerminal(long timeout) throws Exception {
        long deadline = SystemClock.elapsedRealtime() + timeout;
        String lastStage = "";
        while (SystemClock.elapsedRealtime() < deadline) {
            JSONObject status = PanoramaStitchService.getJob(context, jobId, owner);
            String state = status.getString("state");
            double progress = status.getDouble("progress");
            assertTrue(progress >= 0 && progress <= 1);
            String stage = status.optString("stage");
            if (!stage.equals(lastStage)) {
                android.util.Log.i("StitchServiceTest", state + " " + stage + " " + progress);
                lastStage = stage;
            }
            if ("completed".equals(state) || "failed".equals(state) || "cancelled".equals(state)) return status;
            assertTrue("queued".equals(state) || "running".equals(state));
            SystemClock.sleep(500);
        }
        throw new AssertionError("Foreground stitch did not finish within its bounded runtime.");
    }

    private void awaitWorkerReleased() {
        long deadline = SystemClock.elapsedRealtime() + 15_000;
        while (PanoramaStitchService.isSessionActive(session) && SystemClock.elapsedRealtime() < deadline) SystemClock.sleep(100);
        assertFalse("Terminal worker must release its active-session reservation", PanoramaStitchService.isSessionActive(session));
    }

    private void assertImage(String url, int width, int height) throws Exception {
        Uri uri = Uri.parse(url);
        assertEquals("file", uri.getScheme());
        File image = new File(uri.getPath()).getCanonicalFile();
        assertEquals(session, image.getParentFile().getParentFile());
        assertTrue(image.isFile() && image.length() > 0);
        BitmapFactory.Options bounds = new BitmapFactory.Options();
        bounds.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(image.getPath(), bounds);
        assertTrue(bounds.outWidth > 0 && bounds.outHeight > 0);
        if (width > 0) { assertEquals(width, bounds.outWidth); assertEquals(height, bounds.outHeight); }
    }

    private void assertOriginalsUnchanged() throws Exception {
        for (int index = 0; index < originals.size(); index++) {
            assertTrue(originals.get(index).isFile());
            assertArrayEquals(originalDigests.get(index), digest(originals.get(index)));
        }
    }

    private static byte[] digest(File file) throws Exception {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        try (FileInputStream input = new FileInputStream(file)) {
            byte[] buffer = new byte[64 * 1024];
            for (int count; (count = input.read(buffer)) != -1;) digest.update(buffer, 0, count);
        }
        return digest.digest();
    }

    @After public void preserveFixtureAndStopOnlyThisTestsWork() throws Exception {
        try {
            if (jobId != null) PanoramaStitchService.cancel(jobId, owner);
            if (session != null) {
                assertOriginalsUnchanged();
                if (safeToCleanUp && !PanoramaStitchService.isSessionActive(session)) {
                    PanoramaCaptureStore.validateSession(store.getRoot(), session);
                    deleteTestSessionTree(session);
                    android.util.Log.i("StitchServiceTest", "Removed only copied test session; benchmark and outputs retained under " + fixture);
                } else android.util.Log.i("StitchServiceTest", "Retained failed/in-flight synthetic test capture at " + session);
            }
        } finally {
            if (shellIdentity) InstrumentationRegistry.getInstrumentation().getUiAutomation().dropShellPermissionIdentity();
        }
    }

    private void deleteTestSessionTree(File file) throws IOException {
        File canonical = file.getCanonicalFile();
        if (!canonical.equals(file.getAbsoluteFile()) ||
            (!canonical.equals(session) && !canonical.getPath().startsWith(session.getCanonicalPath() + File.separator))) {
            throw new IOException("Refusing to clean anything outside this test's newly created session.");
        }
        File[] children = canonical.listFiles();
        if (children != null) for (File child : children) deleteTestSessionTree(child);
        if (!canonical.delete()) throw new IOException("Could not clean copied test file " + canonical);
    }
}
